name: image_editor
description: Edit your image data and output to file/memory, Use objc/kotlin to handle it.
version: 0.7.2
author: Caijinglong<cjl_spy@163.com>
homepage: https://github.com/fluttercandies/flutter_image_editor

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: top.kikt.flutter_image_editor
    pluginClass: FlutterImageEditorPlugin
