name: image_editor
description: Edit your image data and output to file/memory, Use objc/kotlin to handle it.
version: 1.0.0-nullsafety.0
homepage: https://github.com/fluttercandies/flutter_image_editor

environment:
  sdk: ">=2.12.0-0 <3.0.0"
  flutter: ">=1.22.6"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: top.kikt.flutter_image_editor
        pluginClass: FlutterImageEditorPlugin
      ios:
        pluginClass: FlutterImageEditorPlugin
