name: Add library to new flutter project
on:
  push:
  pull_request:
jobs:
  build-for-macos-3-10-6:
    name: Build for macos with 3.10.6 on macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=macos
        name: Create new project
      - name: Set minimum macOS version
        run: |
              sed -i '' 's/platform :osx, .*/platform :osx, '\''11.0'\''/g' macos/Podfile
              sed -i '' 's/MACOSX_DEPLOYMENT_TARGET = .*;/MACOSX_DEPLOYMENT_TARGET = 11.0;/g' macos/Runner.xcodeproj/project.pbxproj
      - name: Add image_editor to new project.
        run: flutter pub add -- 'image_editor:{"path":"../image_editor"}'
        working-directory: ${{ github.workspace }}/new_project
        shell: bash
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build macos --release
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
  build-for-ios-3-10-6:
    name: Build for ios with 3.10.6 on macos-latest
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.10.6
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
      - run: flutter doctor -v
        name: Flutter info
      - run: flutter create new_project --platforms=ios
        name: Create new project
      - name: Set minimum iOS version
        run: |
              sed -i '' 's/platform :ios, .*/platform :ios, '\''11.0'\''/g' ios/Podfile
              sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = .*;/IPHONEOS_DEPLOYMENT_TARGET = 11.0;/g' ios/Runner.xcodeproj/project.pbxproj
      - name: Add image_editor to new project.
        run: flutter pub add -- 'image_editor:{"path":"../image_editor"}'
        working-directory: ${{ github.workspace }}/new_project
        shell: bash
      - run: flutter pub get
        working-directory: ${{ github.workspace }}/new_project
      - run: flutter build ios --release --no-codesign
        working-directory: ${{ github.workspace }}/new_project
        name: Build example
